const {JSDOM}=require('jsdom');const fs=require('fs');const assert=require('node:assert/strict');
const dom=new JSDOM(fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8'),{url:'https://preview.example.test',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window;w.matchMedia=()=>({matches:false});w.HTMLElement.prototype.scrollTo=function(){};w.HTMLElement.prototype.scrollBy=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
const source=fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8').replace(/^import .*?;\n/gm,'');
const stubs="const initializeApp=()=>({}), getFirestore=()=>({}),getAuth=()=>({}),onAuthStateChanged=()=>{},onSnapshot=()=>()=>{},collection=(...x)=>x,collectionGroup=(...x)=>x,doc=(...x)=>({id:x.at(-1)}),query=(...x)=>x,where=()=>{},orderBy=()=>{},limit=()=>{},serverTimestamp=()=>new Date(),sameBook=(a,b)=>a.title===b.title,searchCatalog=async()=>[],getDoc=async()=>({exists:()=>true,data:()=>({displayName:'Sample reader',bio:'A quiet reading corner.',role:'member',themeColor:'#ff0000',joinedAt:'2026-08-14',showReadingStats:true})});\n\n";
const seed="\nstate.books = ['If Cats Disappeared from the World','The Little Prince','A long book title with unusual punctuation: \u201cStories\u201d, Chapters & More','No Exit','A Gentle Reminder','The Last Olympian','A Book Without a Cover'].map((title,i)=>({id:String(i),title,author:i===0?'Genki Kawamura':'Sample author',genre:i%2?'Fantasy, Adventure':'Fiction',why:'A thoughtful book to read at your own pace. Bring a favorite passage to our next conversation.',synopsis:'A story worth exploring. '.repeat(30),comments:[],date:'2026-09-01',memberId:'reader',memberName:'Sample reader'}));\nstate.currentPickId='0'; state.members=[{id:'reader',displayName:'Sample reader',role:'member'}];\nstate.ratings=[{memberId:'reader',displayName:'Sample reader',stars:4,finished:true,comment:'A memorable ending.'}];\nstate.activities=Array.from({length:7},(_,i)=>({actorId:'reader',type:'recommended_book',bookTitle:state.books[i].title,publicBookId:String(i),bookAuthor:'Sample author',createdAt:new Date().toISOString()}));\nstate.events=[{id:'past',title:'Previous library meeting',date:'2020-01-01',details:'An earlier club gathering.'},{id:'next',title:'Next library meeting',date:'2030-01-01',details:'Sample event for preview only.'}];\nui.announcementText.textContent='Preview only \u2014 sample books and events. No live database is connected.';\nrenderBooks();renderDiscovery();renderActivityFeed();renderEvents();renderMembers();renderBoard();renderMemories();renderReadingGoal();setAuthUi();\n";
w.eval(stubs+source+seed+'\nwindow.fixture={state,renderDiscovery,renderBooks,renderShelf,ui};');
const d=w.document;
assert.equal(d.querySelectorAll('.book-card').length,7);
assert.ok([...d.querySelectorAll('.book-card')].every(x=>x.querySelector('strong')&&x.querySelector('small')));
assert.equal(d.querySelectorAll('.discovery-lane:not([hidden])').length,1);
const selector=d.getElementById('discoveryCategory');selector.selectedIndex=1;selector.dispatchEvent(new w.Event('change'));
assert.equal(d.querySelector('.discovery-lane:not([hidden]) h3').textContent,selector.value);
assert.equal(d.querySelectorAll('.activity-feed > .activity-list > li').length,3);
assert.equal(d.querySelector('.activity-more').open,false);
assert.equal(d.querySelector('.event-archive').open,false);
assert.equal(d.getElementById('monthProgress').textContent,'1 of 1 responding readers finished');
const search=d.getElementById('bookSearch');search.value='not present';search.dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('.book-card').length,0);
search.value='';search.dispatchEvent(new w.Event('input'));
const genre=d.getElementById('genreFilter');genre.value='adventure';genre.dispatchEvent(new w.Event('change'));assert.equal(d.querySelectorAll('.book-card').length,3);
d.querySelector('.book-card').click();assert.equal(d.querySelectorAll('.book-detail > .book-conversation').length,1);assert.ok(d.querySelector('.book-conversation .book-discussion'));
const previous=selector.value;w.fixture.renderDiscovery();assert.equal(selector.value,previous);
w.fixture.state.books=[];w.fixture.renderDiscovery();assert.ok(selector.disabled);
assert.equal(new Set([...d.querySelectorAll('[id]')].map(x=>x.id)).size,d.querySelectorAll('[id]').length);
console.log('PASS: full initialization, shelf labels/search/genre, discovery selection/persistence/empty state, collapsed activity/archive, rating denominator, full-width discussion, unique IDs.');
dom.window.close();
